###
### CI test server configuration
###
### Paths are relative to the config file
### There can be multiple mod_path's and pan_path's
### tick_time is in milliseconds, tick_time = 1000 => 1 second per tick
###

port = 3000
server_name = A sample server
mods_path = ../CItest
pan_path = ../specs/proto
tick_time = 1000

# Enable when debugging
#log_file = ./msva.log
