// GENERATED FILE -- DO NOT EDIT
// Generated by libpan
// Contains:
//  - server srv:tCorrect(...)
//  - client srv:tLocal(...)
//  - server srv:hasPref(...)
//  - server srv:id(...)
//  - server srv:name(...)

#pragma once
#include "libpan_cxx_macros.hpp"

PAN_GH_DEFS_BEGIN

PAN_GH_MSG(PAN_GH_SERVER, srv, tCorrect, "srv", "tCorrect",
    int64_t          client_ns;
    int64_t          server_ns;
)
PAN_GH_DECODE(PAN_GH_SERVER, srv, tCorrect, "srv", "tCorrect",
    PAN_GH_READ(&self->client_ns, sizeof(self->client_ns));
    PAN_GH_READ(&self->server_ns, sizeof(self->server_ns));
)
PAN_GH_ENCODE(PAN_GH_SERVER, srv, tCorrect, "srv", "tCorrect",
    uint16_t len = 0;
    len += sizeof(self->client_ns);
    len += sizeof(self->server_ns);
    PAN_GH_HEADER("srv", "tCorrect", len);
    PAN_GH_WRITE(&self->client_ns, sizeof(self->client_ns));
    PAN_GH_WRITE(&self->server_ns, sizeof(self->server_ns));
)

PAN_GH_MSG(PAN_GH_CLIENT, srv, tLocal, "srv", "tLocal",
    int64_t          client_ns;
)
PAN_GH_DECODE(PAN_GH_CLIENT, srv, tLocal, "srv", "tLocal",
    PAN_GH_READ(&self->client_ns, sizeof(self->client_ns));
)
PAN_GH_ENCODE(PAN_GH_CLIENT, srv, tLocal, "srv", "tLocal",
    uint16_t len = 0;
    len += sizeof(self->client_ns);
    PAN_GH_HEADER("srv", "tLocal", len);
    PAN_GH_WRITE(&self->client_ns, sizeof(self->client_ns));
)

PAN_GH_MSG(PAN_GH_SERVER, srv, hasPref, "srv", "hasPref",
    PAN_GH_CHAR64    pref;
)
PAN_GH_DECODE(PAN_GH_SERVER, srv, hasPref, "srv", "hasPref",
    PAN_GH_READ(&self->pref, sizeof(self->pref));
)
PAN_GH_ENCODE(PAN_GH_SERVER, srv, hasPref, "srv", "hasPref",
    uint16_t len = 0;
    len += sizeof(self->pref);
    PAN_GH_HEADER("srv", "hasPref", len);
    PAN_GH_WRITE(&self->pref, sizeof(self->pref));
)

PAN_GH_MSG(PAN_GH_SERVER, srv, id, "srv", "id",
    PAN_GH_ID        id;
)
PAN_GH_DECODE(PAN_GH_SERVER, srv, id, "srv", "id",
    PAN_GH_READ(&self->id, sizeof(self->id));
)
PAN_GH_ENCODE(PAN_GH_SERVER, srv, id, "srv", "id",
    uint16_t len = 0;
    len += sizeof(self->id);
    PAN_GH_HEADER("srv", "id", len);
    PAN_GH_WRITE(&self->id, sizeof(self->id));
)

PAN_GH_MSG(PAN_GH_SERVER, srv, name, "srv", "name",
    PAN_GH_SLICE     name;
)
PAN_GH_DECODE(PAN_GH_SERVER, srv, name, "srv", "name",
    uint16_t name_len = 0;
    PAN_GH_READ(&name_len, 2);
    PAN_GH_READ_SLICE(&self->name, name_len);
)
PAN_GH_ENCODE(PAN_GH_SERVER, srv, name, "srv", "name",
    uint16_t len = 0;
    len += 2 + PAN_GH_SLICE_LEN(&self->name);
    PAN_GH_HEADER("srv", "name", len);
    uint16_t name_len = PAN_GH_SLICE_LEN(&self->name);
    PAN_GH_WRITE(&name_len, 2);
    PAN_GH_WRITE_SLICE(&self->name, name_len);
)

PAN_GH_DEFS_END
