port = 3000
server_name = Flightsim server
mods_path = ./build/src/syncv/libsyncv.server.so
mods_path = ./build/src/game-server/libgame.server.so
pan_path = .

# Enable when debugging
#log_file = ./msva.log

