// GENERATED FILE -- DO NOT EDIT
// Generated by libpan
// Contains:
//  - server syncv:remove(...)
//  - server syncv:update(...)
//  - server syncv:declare(...)

#pragma once
#include "libpan_cxx_macros.hpp"

PAN_GH_DEFS_BEGIN

PAN_GH_MSG(PAN_GH_SERVER, syncv, remove, "syncv", "remove",
    PAN_GH_ID        scope;
    PAN_GH_ID        var;
    PAN_GH_SLICE     name;
)
PAN_GH_DECODE(PAN_GH_SERVER, syncv, remove, "syncv", "remove",
    PAN_GH_READ(&self->scope, sizeof(self->scope));
    PAN_GH_READ(&self->var, sizeof(self->var));
    uint16_t name_len = 0;
    PAN_GH_READ(&name_len, 2);
    PAN_GH_READ_SLICE(&self->name, name_len);
)
PAN_GH_ENCODE(PAN_GH_SERVER, syncv, remove, "syncv", "remove",
    uint16_t len = 0;
    len += sizeof(self->scope);
    len += sizeof(self->var);
    len += 2 + PAN_GH_SLICE_LEN(&self->name);
    PAN_GH_HEADER("syncv", "remove", len);
    PAN_GH_WRITE(&self->scope, sizeof(self->scope));
    PAN_GH_WRITE(&self->var, sizeof(self->var));
    uint16_t name_len = PAN_GH_SLICE_LEN(&self->name);
    PAN_GH_WRITE(&name_len, 2);
    PAN_GH_WRITE_SLICE(&self->name, name_len);
)

PAN_GH_MSG(PAN_GH_SERVER, syncv, update, "syncv", "update",
    PAN_GH_ID        scope;
    PAN_GH_ID        var;
    int64_t          time;
    int64_t          val;
)
PAN_GH_DECODE(PAN_GH_SERVER, syncv, update, "syncv", "update",
    PAN_GH_READ(&self->scope, sizeof(self->scope));
    PAN_GH_READ(&self->var, sizeof(self->var));
    PAN_GH_READ(&self->time, sizeof(self->time));
    PAN_GH_READ(&self->val, sizeof(self->val));
)
PAN_GH_ENCODE(PAN_GH_SERVER, syncv, update, "syncv", "update",
    uint16_t len = 0;
    len += sizeof(self->scope);
    len += sizeof(self->var);
    len += sizeof(self->time);
    len += sizeof(self->val);
    PAN_GH_HEADER("syncv", "update", len);
    PAN_GH_WRITE(&self->scope, sizeof(self->scope));
    PAN_GH_WRITE(&self->var, sizeof(self->var));
    PAN_GH_WRITE(&self->time, sizeof(self->time));
    PAN_GH_WRITE(&self->val, sizeof(self->val));
)

PAN_GH_MSG(PAN_GH_SERVER, syncv, declare, "syncv", "declare",
    PAN_GH_ID        scope;
    PAN_GH_ID        var;
    int8_t           type;
    PAN_GH_SLICE     name;
)
PAN_GH_DECODE(PAN_GH_SERVER, syncv, declare, "syncv", "declare",
    PAN_GH_READ(&self->scope, sizeof(self->scope));
    PAN_GH_READ(&self->var, sizeof(self->var));
    PAN_GH_READ(&self->type, sizeof(self->type));
    uint16_t name_len = 0;
    PAN_GH_READ(&name_len, 2);
    PAN_GH_READ_SLICE(&self->name, name_len);
)
PAN_GH_ENCODE(PAN_GH_SERVER, syncv, declare, "syncv", "declare",
    uint16_t len = 0;
    len += sizeof(self->scope);
    len += sizeof(self->var);
    len += sizeof(self->type);
    len += 2 + PAN_GH_SLICE_LEN(&self->name);
    PAN_GH_HEADER("syncv", "declare", len);
    PAN_GH_WRITE(&self->scope, sizeof(self->scope));
    PAN_GH_WRITE(&self->var, sizeof(self->var));
    PAN_GH_WRITE(&self->type, sizeof(self->type));
    uint16_t name_len = PAN_GH_SLICE_LEN(&self->name);
    PAN_GH_WRITE(&name_len, 2);
    PAN_GH_WRITE_SLICE(&self->name, name_len);
)

PAN_GH_DEFS_END
