// GENERATED FILE -- DO NOT EDIT
// Generated by libpan
// Contains:
//  - server bomber:wall(...)
//  - server bomber:sees(...)
//  - server bomber:at(...)
//  - server bomber:hp(...)
//  - server bomber:tick(...)
//  - client bomber:bomb(...)
//  - client bomber:move(...)

#pragma once
#include "libpan_cxx_macros.hpp"

PAN_GH_DEFS_BEGIN

PAN_GH_MSG(PAN_GH_SERVER, bomber, wall, "bomber", "wall",
    int32_t          x;
    int32_t          y;
)
PAN_GH_DECODE(PAN_GH_SERVER, bomber, wall, "bomber", "wall",
    PAN_GH_READ(&self->x, sizeof(self->x));
    PAN_GH_READ(&self->y, sizeof(self->y));
)
PAN_GH_ENCODE(PAN_GH_SERVER, bomber, wall, "bomber", "wall",
    uint16_t len = 0;
    len += sizeof(self->x);
    len += sizeof(self->y);
    PAN_GH_HEADER("bomber", "wall", len);
    PAN_GH_WRITE(&self->x, sizeof(self->x));
    PAN_GH_WRITE(&self->y, sizeof(self->y));
)

PAN_GH_MSG(PAN_GH_SERVER, bomber, sees, "bomber", "sees",
    int32_t          x;
    int32_t          y;
    PAN_GH_ID        who;
)
PAN_GH_DECODE(PAN_GH_SERVER, bomber, sees, "bomber", "sees",
    PAN_GH_READ(&self->x, sizeof(self->x));
    PAN_GH_READ(&self->y, sizeof(self->y));
    PAN_GH_READ(&self->who, sizeof(self->who));
)
PAN_GH_ENCODE(PAN_GH_SERVER, bomber, sees, "bomber", "sees",
    uint16_t len = 0;
    len += sizeof(self->x);
    len += sizeof(self->y);
    len += sizeof(self->who);
    PAN_GH_HEADER("bomber", "sees", len);
    PAN_GH_WRITE(&self->x, sizeof(self->x));
    PAN_GH_WRITE(&self->y, sizeof(self->y));
    PAN_GH_WRITE(&self->who, sizeof(self->who));
)

PAN_GH_MSG(PAN_GH_SERVER, bomber, at, "bomber", "at",
    int32_t          x;
    int32_t          y;
)
PAN_GH_DECODE(PAN_GH_SERVER, bomber, at, "bomber", "at",
    PAN_GH_READ(&self->x, sizeof(self->x));
    PAN_GH_READ(&self->y, sizeof(self->y));
)
PAN_GH_ENCODE(PAN_GH_SERVER, bomber, at, "bomber", "at",
    uint16_t len = 0;
    len += sizeof(self->x);
    len += sizeof(self->y);
    PAN_GH_HEADER("bomber", "at", len);
    PAN_GH_WRITE(&self->x, sizeof(self->x));
    PAN_GH_WRITE(&self->y, sizeof(self->y));
)

PAN_GH_MSG(PAN_GH_SERVER, bomber, hp, "bomber", "hp",
    int32_t          val;
)
PAN_GH_DECODE(PAN_GH_SERVER, bomber, hp, "bomber", "hp",
    PAN_GH_READ(&self->val, sizeof(self->val));
)
PAN_GH_ENCODE(PAN_GH_SERVER, bomber, hp, "bomber", "hp",
    uint16_t len = 0;
    len += sizeof(self->val);
    PAN_GH_HEADER("bomber", "hp", len);
    PAN_GH_WRITE(&self->val, sizeof(self->val));
)

PAN_GH_MSG(PAN_GH_SERVER, bomber, tick, "bomber", "tick",
)
PAN_GH_DECODE(PAN_GH_SERVER, bomber, tick, "bomber", "tick",
)
PAN_GH_ENCODE(PAN_GH_SERVER, bomber, tick, "bomber", "tick",
    uint16_t len = 0;
    PAN_GH_HEADER("bomber", "tick", len);
)

PAN_GH_MSG(PAN_GH_CLIENT, bomber, bomb, "bomber", "bomb",
)
PAN_GH_DECODE(PAN_GH_CLIENT, bomber, bomb, "bomber", "bomb",
)
PAN_GH_ENCODE(PAN_GH_CLIENT, bomber, bomb, "bomber", "bomb",
    uint16_t len = 0;
    PAN_GH_HEADER("bomber", "bomb", len);
)

PAN_GH_MSG(PAN_GH_CLIENT, bomber, move, "bomber", "move",
    int8_t           dx;
    int8_t           dy;
)
PAN_GH_DECODE(PAN_GH_CLIENT, bomber, move, "bomber", "move",
    PAN_GH_READ(&self->dx, sizeof(self->dx));
    PAN_GH_READ(&self->dy, sizeof(self->dy));
)
PAN_GH_ENCODE(PAN_GH_CLIENT, bomber, move, "bomber", "move",
    uint16_t len = 0;
    len += sizeof(self->dx);
    len += sizeof(self->dy);
    PAN_GH_HEADER("bomber", "move", len);
    PAN_GH_WRITE(&self->dx, sizeof(self->dx));
    PAN_GH_WRITE(&self->dy, sizeof(self->dy));
)

PAN_GH_DEFS_END
