# Sample server configuration
# Paths are relative to config file
port = 3000
server_name = A sample server
mods_dir = build/
pan_dir = ./specs/proto/srv.pan
pan_dir = ./specs/proto/role.pan
pan_dir = ./mods/characters/ghost/proto/ghost.pan
pan_dir = ./mods/characters/pacman/proto/pacman.pan
pan_dir = ./mods/characters/person/proto/person.pan
