// GENERATED FILE -- DO NOT EDIT
// Generated by libpan
// Contains:
//  - server game:despawn(...)
//  - server game:spawn(...)
//  - client game:rotate(...)
//  - client game:command(...)

#pragma once
#include "libpan_cxx_macros.hpp"

PAN_GH_DEFS_BEGIN

PAN_GH_MSG(PAN_GH_SERVER, game, despawn, "game", "despawn",
    PAN_GH_ID        id;
)
PAN_GH_DECODE(PAN_GH_SERVER, game, despawn, "game", "despawn",
    PAN_GH_READ(&self->id, sizeof(self->id));
)
PAN_GH_ENCODE(PAN_GH_SERVER, game, despawn, "game", "despawn",
    uint16_t len = 0;
    len += sizeof(self->id);
    PAN_GH_HEADER("game", "despawn", len);
    PAN_GH_WRITE(&self->id, sizeof(self->id));
)

PAN_GH_MSG(PAN_GH_SERVER, game, spawn, "game", "spawn",
    PAN_GH_ID        id;
)
PAN_GH_DECODE(PAN_GH_SERVER, game, spawn, "game", "spawn",
    PAN_GH_READ(&self->id, sizeof(self->id));
)
PAN_GH_ENCODE(PAN_GH_SERVER, game, spawn, "game", "spawn",
    uint16_t len = 0;
    len += sizeof(self->id);
    PAN_GH_HEADER("game", "spawn", len);
    PAN_GH_WRITE(&self->id, sizeof(self->id));
)

PAN_GH_MSG(PAN_GH_CLIENT, game, rotate, "game", "rotate",
    double           azimuth;
    double           elevation;
)
PAN_GH_DECODE(PAN_GH_CLIENT, game, rotate, "game", "rotate",
    PAN_GH_READ(&self->azimuth, sizeof(self->azimuth));
    PAN_GH_READ(&self->elevation, sizeof(self->elevation));
)
PAN_GH_ENCODE(PAN_GH_CLIENT, game, rotate, "game", "rotate",
    uint16_t len = 0;
    len += sizeof(self->azimuth);
    len += sizeof(self->elevation);
    PAN_GH_HEADER("game", "rotate", len);
    PAN_GH_WRITE(&self->azimuth, sizeof(self->azimuth));
    PAN_GH_WRITE(&self->elevation, sizeof(self->elevation));
)

PAN_GH_MSG(PAN_GH_CLIENT, game, command, "game", "command",
    PAN_GH_CHAR64    action;
)
PAN_GH_DECODE(PAN_GH_CLIENT, game, command, "game", "command",
    PAN_GH_READ(&self->action, sizeof(self->action));
)
PAN_GH_ENCODE(PAN_GH_CLIENT, game, command, "game", "command",
    uint16_t len = 0;
    len += sizeof(self->action);
    PAN_GH_HEADER("game", "command", len);
    PAN_GH_WRITE(&self->action, sizeof(self->action));
)

PAN_GH_DEFS_END
